name       : python-babel
version    : 2.10.1
release    : 15
source     :
    - https://github.com/python-babel/babel/archive/refs/tags/v2.10.1.tar.gz : 7a61207b1d269a09462313ef3065d7bc1b54c9a14ae00f5006e169639674b230
    - https://www.unicode.org/Public/cldr/41/cldr-common-41.0.zip : 823c6170c41e2de2c229574e8a436332d25f1c9723409867fe721e00bc92d853
    - https://www.unicode.org/Public/cldr/41/core.zip : 823c6170c41e2de2c229574e8a436332d25f1c9723409867fe721e00bc92d853
homepage   : https://babel.pocoo.org
license    : BSD-3-Clause
component  : programming.python
summary    : A collection of tools for internationalizing Python applications
description: |
    Babel is an integrated collection of utilities that assist in internationalizing and localizing Python applications, with an emphasis on web-based applications.
builddeps  :
    - pkgconfig(python3)
    - python-freezegun
    - python-pytest
    - python-pytz
rundeps    :
    - python-pytz
setup      : |
    cp $sources/cldr-common-41.0.zip $workdir/cldr/cldr-common-41.0.zip
    cp $sources/core.zip $workdir/cldr/cldr-core-37.zip
build      : |
    %python3_setup import_cldr
install    : |
    %python3_install
check      : |
    %python3_test pytest3
