name       : python-babel
version    : 2.12.1
release    : 18
source     :
    - https://github.com/python-babel/babel/archive/refs/tags/v2.12.1.tar.gz : 37de3435fdec7c3267430765fc3ebe05cd234e65774ff1dc42a7b3b5cd39ef97
    - https://unicode.org/Public/cldr/42/cldr-common-42.0.zip : 53cd4fd1ac2ee4d4cbcae362e7af5d02e98e5e39c826ce9d723d41ca836fc846
    - https://www.unicode.org/Public/cldr/42/core.zip : 53cd4fd1ac2ee4d4cbcae362e7af5d02e98e5e39c826ce9d723d41ca836fc846
homepage   : https://babel.pocoo.org
license    : BSD-3-Clause
component  : programming.python
summary    : A collection of tools for internationalizing Python applications
description: |
    Babel is an integrated collection of utilities that assist in internationalizing and localizing Python applications, with an emphasis on web-based applications.
builddeps  :
    - python-freezegun   # check
    - python-pytest      # check
    - python-pytz        # check
setup      : |
    %patch -p1 < $pkgfiles/fix-test.patch
    cp $sources/cldr-common-42.0.zip $workdir/cldr/cldr-common-42.0.zip
    cp $sources/core.zip $workdir/cldr/cldr-core-37.zip
build      : |
    %python3_setup import_cldr
install    : |
    %python3_install
check      : |
    %python3_test pytest3
