name       : python-babel
version    : 2.9.0
release    : 11
source     :
    - https://github.com/python-babel/babel/archive/v2.9.0.tar.gz : 7df55ebc7a75b6c544c381e1cc07151c2429f73f4ed01107bd8998b96cc83f42
    - https://www.unicode.org/Public/cldr/37/core.zip : ba93f5ba256a61a6f8253397c6c4b1a9b9e77531f013cc7ffa7977b5f7e4da57
license    : BSD-3-Clause
component  : programming.python
summary    : Babel is a collection of tools for internationalizing Python applications.
description: |
    Babel is a collection of tools for internationalizing Python applications.
builddeps  :
    - pkgconfig(python3)
    - python-freezegun
    - python-setuptools
    - python-pytest
    - python-pytz
rundeps    :
    - python-pytz
setup      : |
    cp $sources/core.zip $workdir/cldr/cldr-core-37.zip
build      : |
    %python_setup import_cldr
    %python3_setup import_cldr
install    : |
    %python_install
    %python3_install
#check      : |
#    %python_test pytest
#    %python3_test pytest3
