name       : python-babel
version    : 2.3.4
release    : 2
source     :
    - https://github.com/python-babel/babel/archive/2.3.4.tar.gz : 41a206f3d4305556a6f103afe04143928ed6663109acfc30ebb4064acb8a4e33
    - http://unicode.org/Public/cldr/28/core.zip : 26f751ab1421192b2ae76c5fd2f83ad477d611c5711098f4fe0ec09c9602ff4d
license    : BSD-3-Clause
component  : programming.python
summary    : Babel is a collection of tools for internationalizing Python applications.
description: |
    Babel is a collection of tools for internationalizing Python applications.
builddeps  :
    - pkgconfig(python-2.7)
    - python-setuptools
    - python-pytz
rundeps    :
    - python-pytz
setup: |
    mv $sources/core.zip $workdir/cldr/core-28.zip
build      : |
    %python_setup import_cldr
install    : |
    %python_install
