name       : python-babel
version    : 2.6.0
release    : 6
source     :
    - https://files.pythonhosted.org/packages/be/cc/9c981b249a455fa0c76338966325fc70b7265521bad641bf2932f77712f4/Babel-2.6.0.tar.gz : 8cba50f48c529ca3fa18cf81fa9403be176d374ac4d60738b839122dfaaa3d23
    - https://www.unicode.org/Public/cldr/33/core.zip : fa3490082c086d21257153609642f54fcf788fcfda4966fe67f3f6daca0d58b9
license    : BSD-3-Clause
component  : programming.python
summary    : Babel is a collection of tools for internationalizing Python applications.
description: |
    Babel is a collection of tools for internationalizing Python applications.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
    - python-pytz
rundeps    :
    - python-pytz
setup      : |
    mkdir $workdir/cldr
    cp $sources/core.zip $workdir/cldr/core-33.0.zip
build      : |
    %python_setup import_cldr
    %python3_setup import_cldr
install    : |
    %python_install
    %python3_install
