name       : python-babel
version    : 2.9.1
release    : 13
source     :
    - https://github.com/python-babel/babel/archive/v2.9.1.tar.gz : 96102878b273d0160c210d9323406d26c4a5cf0f5d3a0097a059836a624231f9
    - https://www.unicode.org/Public/cldr/37/core.zip : ba93f5ba256a61a6f8253397c6c4b1a9b9e77531f013cc7ffa7977b5f7e4da57
license    : BSD-3-Clause
component  : programming.python
summary    : Babel is a collection of tools for internationalizing Python applications.
description: |
    Babel is a collection of tools for internationalizing Python applications.
builddeps  :
    - pkgconfig(python3)
    - python-freezegun
    - python-pytest
    - python-pytz
rundeps    :
    - python-pytz
setup      : |
    cp $sources/core.zip $workdir/cldr/cldr-core-37.zip
build      : |
    %python3_setup import_cldr
install    : |
    %python3_install
check      : |
    %python3_test pytest3
