name       : python-babel
version    : 2.4.0
release    : 3
source     :
    - https://pypi.python.org/packages/92/22/643f3b75f75e0220c5ef9f5b72b619ccffe9266170143a4821d4885198de/Babel-2.4.0.tar.gz : 8c98f5e5f8f5f088571f2c6bd88d530e331cbbcb95a7311a0db69d3dca7ec563
    - http://unicode.org/Public/cldr/29/core.zip : b3308f8d3b4a80045ce4262b2784ac8d99775e80aaacafbf1277833f6b28ffda
license    : BSD-3-Clause
component  : programming.python
summary    : Babel is a collection of tools for internationalizing Python applications.
description: |
    Babel is a collection of tools for internationalizing Python applications.
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools
    - python-pytz
rundeps    :
    - python-pytz
setup      : |
    mkdir $workdir/cldr
    cp $sources/core.zip $workdir/cldr/core-29.zip
build      : |
    %python_setup import_cldr
    %python3_setup import_cldr
install    : |
    %python_install
    %python3_install
