name       : python-babel
version    : 2.7.0
release    : 9
source     :
    - https://github.com/python-babel/babel/releases/download/v2.7.0/Babel-2.7.0.tar.gz : e86135ae101e31e2c8ec20a4e0c5220f4eed12487d5cf3f78be7e98d3a57fc28
    - https://www.unicode.org/Public/cldr/35.1/core.zip : e2ede8cb8f9c29157e281ee9e696ce540a72c598841bed595a406b710eea87b0
license    : BSD-3-Clause
component  : programming.python
summary    : Babel is a collection of tools for internationalizing Python applications.
description: |
    Babel is a collection of tools for internationalizing Python applications.
builddeps  :
    - pkgconfig(python3)
    - python-freezegun
    - python-setuptools
    - python-pytest
    - python-pytz
rundeps    :
    - python-pytz
setup      : |
    mkdir cldr
    cp $sources/core.zip $workdir/cldr/cldr-core-35.1.zip
build      : |
    %python_setup import_cldr
    %python3_setup import_cldr
install    : |
    %python_install
    %python3_install
#check      : |
#    %python_test pytest
#    %python3_test pytest3
