name       : python-babel
version    : 2.6.0
release    : 7
source     :
    - https://github.com/python-babel/babel/archive/v2.6.0.tar.gz : f760326e6ae6ce290520aef63c3ee416a9258d7917addb0b6e086fe0e5911432
    - https://www.unicode.org/Public/cldr/33/core.zip : fa3490082c086d21257153609642f54fcf788fcfda4966fe67f3f6daca0d58b9
license    : BSD-3-Clause
component  : programming.python
summary    : Babel is a collection of tools for internationalizing Python applications.
description: |
    Babel is a collection of tools for internationalizing Python applications.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
    - python-pytz
rundeps    :
    - python-pytz
setup      : |
    cp $sources/core.zip $workdir/cldr/core-33.0.zip
build      : |
    %python_setup import_cldr
    %python3_setup import_cldr
install    : |
    %python_install
    %python3_install
