name       : python-babel
version    : 2.3.4
release    : 1
source     :
    - https://github.com/python-babel/babel/archive/2.3.4.tar.gz : 41a206f3d4305556a6f103afe04143928ed6663109acfc30ebb4064acb8a4e33
license    : BSD-3-Clause
component  : programming.python
summary    : Babel is a collection of tools for internationalizing Python applications.
description: |
    Babel is a collection of tools for internationalizing Python applications.
builddeps  :
    - pkgconfig(python-2.7)
    - python-setuptools
    - python-pytz
rundeps    :
    - python-pytz
build      : |
    %python_setup
install    : |
    %python_install
